[PR] Deleting Projects and Handling an Empty Project List
psperber94/timetrk pull request #6
Opened 2020-09-17 13:23 UTC by anjakDev

1. Projects can be deleted one by one using the delete button in the project view.
2. If all projects are deleted/no projects are in the project list, a separate view is shown to the user. 
3. Creating new projects from an empty lists works without bugs.

2020-09-17 13:24 UTC, anjakDev commented on src/App.vue
> +import EmptyProjectListView from "@/components/views/EmptyProjectListView.vue";
I just reordered the imports to group the views.

2020-09-20 15:37 UTC, psperber94 requested changes
Good stuff

2020-09-20 15:37 UTC, psperber94 commented on src/App.vue
> +          <v-col v-if="projects.length">
I propose to use `v-else` instead.

2020-09-20 15:37 UTC, psperber94 commented on src/components/views/EmptyProjectListView.vue
> +      <img src="@/assets/undraw_stepping_up.svg" height="200px" style="opacity: 0.8" />
Love it 🥇

2020-09-20 17:07 UTC, merged